/**
 * Database initialization
 * RECHECK THIS AS riTriples NEEDS OTHER CHARACTER SET
 */
ALTER DATABASE ${escidoc.database.name} CHARACTER SET UTF8;
/**
 * create eSciDoc DB user and schemas
 */  
CREATE USER "${escidoc.database.userid}" 
IDENTIFIED BY '${escidoc.database.password}' 
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS; 

GRANT CONNECT,RESOURCE, create any table TO "${escidoc.database.userid}";

CREATE USER aa IDENTIFIED BY aa 
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON USERS; 

CREATE USER adm IDENTIFIED BY adm 
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON USERS; 

CREATE USER oai IDENTIFIED BY oai 
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON USERS; 

CREATE USER om IDENTIFIED BY om 
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON USERS; 

CREATE USER sm IDENTIFIED BY sm 
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON USERS; 

CREATE USER st IDENTIFIED BY st 
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON USERS; 


/**
 * create Fedora DB user role
 */  
CREATE ROLE "${fedora.database.userid}" LOGIN 
	PASSWORD '${fedora.database.password}' 
	NOINHERIT CREATEDB VALID UNTIL 'infinity';    

/**
 * create Fedora database
 */
CREATE DATABASE "${fedora.database.name}" WITH ENCODING='UTF8' 
	OWNER="${fedora.database.userid}";   

/**
 * create triple-store database
 */ 
CREATE DATABASE "riTriples" WITH ENCODING='SQL_ASCII' 
	OWNER="${fedora.database.userid}" TEMPLATE=template0;
    