/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.sm.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for AggregationDefinitionHandler.
 */
public interface AggregationDefinitionHandlerRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/AggregationDefinitionHandler";
    public static final String JNDI_NAME = "ejb/AggregationDefinitionHandler";

    public AggregationDefinitionHandlerRemote create()
            throws CreateException, RemoteException;

}
