/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.sm.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * Local home interface for PreprocessingHandler.
 */
public interface PreprocessingHandlerLocalHome extends EJBLocalHome {

    public static final String COMP_NAME = "java:comp/env/ejb/PreprocessingHandlerLocal";
    public static final String JNDI_NAME = "ejb/PreprocessingHandlerLocal";

    public PreprocessingHandlerLocal create() throws CreateException;

}
