/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.sm.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for ReportHandler.
 */
public interface ReportHandlerRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/ReportHandler";
    public static final String JNDI_NAME = "ejb/ReportHandler";

    public ReportHandlerRemote create()
            throws CreateException, RemoteException;

}
