/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.sm.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * Local home interface for ReportDefinitionHandler.
 */
public interface ReportDefinitionHandlerLocalHome extends EJBLocalHome {

    public static final String COMP_NAME = "java:comp/env/ejb/ReportDefinitionHandlerLocal";
    public static final String JNDI_NAME = "ejb/ReportDefinitionHandlerLocal";

    public ReportDefinitionHandlerLocal create() throws CreateException;

}
