/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.sm.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for ScopeHandler.
 */
public interface ScopeHandlerRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/ScopeHandler";
    public static final String JNDI_NAME = "ejb/ScopeHandler";

    public ScopeHandlerRemote create()
            throws CreateException, RemoteException;

}
