/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.sm.ejb.interfaces;

import de.escidoc.core.common.exceptions.application.invalid.InvalidSearchQueryException;
import de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException;
import de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException;
import de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException;
import de.escidoc.core.common.exceptions.application.notfound.ScopeNotFoundException;
import de.escidoc.core.common.exceptions.application.security.AuthenticationException;
import de.escidoc.core.common.exceptions.application.security.AuthorizationException;
import de.escidoc.core.common.exceptions.system.SystemException;
import org.springframework.security.context.SecurityContext;

import javax.ejb.EJBObject;
import java.rmi.RemoteException;
import java.util.Map;

/**
 * Remote interface for ScopeHandler.
 */
public interface ScopeHandlerRemote extends EJBObject {

    public String create(String xmlData,
                                   SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            XmlSchemaValidationException,
            XmlCorruptedException,
            MissingMethodParameterException,
            SystemException, RemoteException;

    public String create(String xmlData, String authHandle, Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            XmlSchemaValidationException,
            XmlCorruptedException,
            MissingMethodParameterException,
            SystemException, RemoteException;

    public void delete(String id, SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            ScopeNotFoundException,
            MissingMethodParameterException,
            SystemException, RemoteException;

    public void delete(String id, String authHandle, Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            ScopeNotFoundException,
            MissingMethodParameterException,
            SystemException, RemoteException;

    public String retrieve(String id,
                                     SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            ScopeNotFoundException,
            MissingMethodParameterException,
            SystemException, RemoteException;

    public String retrieve(String id, String authHandle, Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            ScopeNotFoundException,
            MissingMethodParameterException,
            SystemException, RemoteException;

    public String retrieveScopes(Map parameters,
                                           SecurityContext securityContext)
            throws InvalidSearchQueryException,
            MissingMethodParameterException,
            AuthenticationException,
            AuthorizationException,
            SystemException, RemoteException;

    public String retrieveScopes(Map parameters, String authHandle,
                                           Boolean restAccess)
            throws InvalidSearchQueryException,
            MissingMethodParameterException,
            AuthenticationException,
            AuthorizationException,
            SystemException, RemoteException;

    public String update(String id, String xmlData,
                                   SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            ScopeNotFoundException,
            MissingMethodParameterException,
            XmlSchemaValidationException,
            XmlCorruptedException,
            SystemException, RemoteException;

    public String update(String id, String xmlData, String authHandle,
                                   Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            ScopeNotFoundException,
            MissingMethodParameterException,
            XmlSchemaValidationException,
            XmlCorruptedException,
            SystemException, RemoteException;

}
