/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.sm.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * Local home interface for ScopeHandler.
 */
public interface ScopeHandlerLocalHome extends EJBLocalHome {

    public static final String COMP_NAME = "java:comp/env/ejb/ScopeHandlerLocal";
    public static final String JNDI_NAME = "ejb/ScopeHandlerLocal";

    public ScopeHandlerLocal create() throws CreateException;

}
