/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.sm.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * Local home interface for StatisticDataHandler.
 */
public interface StatisticDataHandlerLocalHome extends EJBLocalHome {

    public static final String COMP_NAME = "java:comp/env/ejb/StatisticDataHandlerLocal";
    public static final String JNDI_NAME = "ejb/StatisticDataHandlerLocal";

    public StatisticDataHandlerLocal create() throws CreateException;

}
