/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.st.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for StagingFileHandler.
 */
public interface StagingFileHandlerRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/StagingFileHandler";
    public static final String JNDI_NAME = "ejb/StagingFileHandler";

    public StagingFileHandlerRemote create()
            throws CreateException, RemoteException;

}
