/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.st.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * Local home interface for StagingFileHandler.
 */
public interface StagingFileHandlerLocalHome extends EJBLocalHome {

    public static final String COMP_NAME = "java:comp/env/ejb/StagingFileHandlerLocal";
    public static final String JNDI_NAME = "ejb/StagingFileHandlerLocal";

    public StagingFileHandlerLocal create() throws CreateException;

}
