/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.aa.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for PolicyDecisionPoint.
 */
public interface PolicyDecisionPointRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/PolicyDecisionPoint";
    public static final String JNDI_NAME = "ejb/PolicyDecisionPoint";

    public PolicyDecisionPointRemote create()
            throws CreateException, RemoteException;

}
