/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.aa.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * Local home interface for PolicyDecisionPoint.
 */
public interface PolicyDecisionPointLocalHome extends EJBLocalHome {

    public static final String COMP_NAME = "java:comp/env/ejb/PolicyDecisionPointLocal";
    public static final String JNDI_NAME = "ejb/PolicyDecisionPointLocal";

    public PolicyDecisionPointLocal create() throws CreateException;

}
