/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.aa.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for RoleHandler.
 */
public interface RoleHandlerRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/RoleHandler";
    public static final String JNDI_NAME = "ejb/RoleHandler";

    public RoleHandlerRemote create()
            throws CreateException, RemoteException;

}
