/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.aa.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * Local home interface for RoleHandler.
 */
public interface RoleHandlerLocalHome extends EJBLocalHome {

    public static final String COMP_NAME = "java:comp/env/ejb/RoleHandlerLocal";
    public static final String JNDI_NAME = "ejb/RoleHandlerLocal";

    public RoleHandlerLocal create() throws CreateException;

}
