/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.aa.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for UserManagementWrapper.
 */
public interface UserManagementWrapperRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/UserManagementWrapper";
    public static final String JNDI_NAME = "ejb/UserManagementWrapper";

    public UserManagementWrapperRemote create()
            throws CreateException, RemoteException;

}
