/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.aa.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for UserGroupHandler.
 */
public interface UserGroupHandlerRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/UserGroupHandler";
    public static final String JNDI_NAME = "ejb/UserGroupHandler";

    public UserGroupHandlerRemote create()
            throws CreateException, RemoteException;

}
