/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.aa.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * Local home interface for UserAccountHandler.
 */
public interface UserAccountHandlerLocalHome extends EJBLocalHome {

    public static final String COMP_NAME = "java:comp/env/ejb/UserAccountHandlerLocal";
    public static final String JNDI_NAME = "ejb/UserAccountHandlerLocal";

    public UserAccountHandlerLocal create() throws CreateException;

}
