/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.oum.ejb;

import javax.ejb.SessionBean;
import javax.ejb.SessionContext;
import java.rmi.RemoteException;

/**
 * Session layer for OrganizationalUnitHandler.
 */
public class OrganizationalUnitHandlerSession extends OrganizationalUnitHandlerBean {

    public void ejbActivate() throws RemoteException {

        super.ejbActivate();
    }

    public void ejbPassivate() throws RemoteException {
        super.ejbPassivate();
    }

    public void setSessionContext(final SessionContext ctx) throws RemoteException {
        super.setSessionContext(ctx);
    }

    public void unsetSessionContext() {
    }

    public void ejbRemove() throws RemoteException {
        super.ejbRemove();
    }

}
