/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.tme.ejb.interfaces;

import de.escidoc.core.common.exceptions.application.invalid.TmeException;
import de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException;
import de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException;
import de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException;
import de.escidoc.core.common.exceptions.application.security.AuthenticationException;
import de.escidoc.core.common.exceptions.application.security.AuthorizationException;
import de.escidoc.core.common.exceptions.system.SystemException;
import org.springframework.security.context.SecurityContext;

import javax.ejb.EJBObject;
import java.rmi.RemoteException;

/**
 * Remote interface for JhoveHandler.
 */
public interface JhoveHandlerRemote extends EJBObject {

    String extract(String requests, SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            XmlCorruptedException,
            XmlSchemaValidationException,
            MissingMethodParameterException,
            SystemException,
            TmeException, RemoteException;

    String extract(String requests, String authHandle, Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            XmlCorruptedException,
            XmlSchemaValidationException,
            MissingMethodParameterException,
            SystemException,
            TmeException, RemoteException;

}
