/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.tme.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for JhoveHandler.
 */
public interface JhoveHandlerRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/JhoveHandler";
    public static final String JNDI_NAME = "ejb/JhoveHandler";

    public JhoveHandlerRemote create()
            throws CreateException, RemoteException;

}
