/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.adm.ejb.interfaces;

import de.escidoc.core.common.exceptions.application.invalid.InvalidSearchQueryException;
import de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException;
import de.escidoc.core.common.exceptions.application.security.AuthenticationException;
import de.escidoc.core.common.exceptions.application.security.AuthorizationException;
import de.escidoc.core.common.exceptions.system.SystemException;
import org.springframework.security.context.SecurityContext;

import javax.ejb.EJBLocalObject;

/**
 * Local interface for AdminHandler.
 */
public interface AdminHandlerLocal extends EJBLocalObject {

    public String deleteObjects(String taskParam,
                                          SecurityContext securityContext)
            throws InvalidXmlException,
            SystemException,
            AuthenticationException,
            AuthorizationException;

    public String deleteObjects(String taskParam, String authHandle,
                                          Boolean restAccess)
            throws InvalidXmlException,
            SystemException,
            AuthenticationException,
            AuthorizationException;

    public String getPurgeStatus(SecurityContext securityContext)
            throws SystemException,
            AuthenticationException,
            AuthorizationException;

    public String getPurgeStatus(String authHandle, Boolean restAccess)
            throws SystemException,
            AuthenticationException,
            AuthorizationException;

    public String getReindexStatus(SecurityContext securityContext)
            throws SystemException,
            AuthenticationException,
            AuthorizationException;

    public String getReindexStatus(String authHandle, Boolean restAccess)
            throws SystemException,
            AuthenticationException,
            AuthorizationException;

    public void decreaseReindexStatus(String objectTypeXml,
                                      SecurityContext securityContext)
            throws InvalidXmlException,
            SystemException,
            AuthenticationException,
            AuthorizationException;

    public void decreaseReindexStatus(String objectTypeXml, String authHandle,
                                      Boolean restAccess)
            throws InvalidXmlException,
            SystemException,
            AuthenticationException,
            AuthorizationException;

    public String reindex(String clearIndex, String indexNamePrefix,
                                    SecurityContext securityContext)
            throws SystemException,
            InvalidSearchQueryException,
            AuthenticationException,
            AuthorizationException;

    public String reindex(String clearIndex, String indexNamePrefix,
                                    String authHandle, Boolean restAccess)
            throws SystemException,
            InvalidSearchQueryException,
            AuthenticationException,
            AuthorizationException;

    public String getIndexConfiguration(SecurityContext securityContext)
            throws SystemException,
            AuthenticationException,
            AuthorizationException;

    public String getIndexConfiguration(String authHandle, Boolean restAccess)
            throws SystemException,
            AuthenticationException,
            AuthorizationException;

    public String getRepositoryInfo(SecurityContext securityContext)
            throws SystemException,
            AuthenticationException,
            AuthorizationException;

    public String getRepositoryInfo(String authHandle, Boolean restAccess)
            throws SystemException,
            AuthenticationException,
            AuthorizationException;

    public String loadExamples(String type,
                                         SecurityContext securityContext)
            throws InvalidSearchQueryException,
            SystemException,
            AuthenticationException,
            AuthorizationException;

    public String loadExamples(String type, String authHandle,
                                         Boolean restAccess)
            throws InvalidSearchQueryException,
            SystemException,
            AuthenticationException,
            AuthorizationException;

}
