/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.adm.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * Local home interface for AdminHandler.
 */
public interface AdminHandlerLocalHome extends EJBLocalHome {

    public static final String COMP_NAME = "java:comp/env/ejb/AdminHandlerLocal";
    public static final String JNDI_NAME = "ejb/AdminHandlerLocal";

    public AdminHandlerLocal create() throws CreateException;

}
