/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.sm.service;

/**
 * Service endpoint interface for AggregationDefinitionHandler.
 */
public interface AggregationDefinitionHandlerService extends java.rmi.Remote {

    java.lang.String create(java.lang.String xmlData,
                            org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.notfound.ScopeNotFoundException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String create(java.lang.String xmlData, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.notfound.ScopeNotFoundException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    void delete(java.lang.String id, org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.notfound.AggregationDefinitionNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    void delete(java.lang.String id, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.notfound.AggregationDefinitionNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieve(java.lang.String id, org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.notfound.AggregationDefinitionNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieve(java.lang.String id, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.notfound.AggregationDefinitionNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveAggregationDefinitions(java.util.Map parameters,
                                                    org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.invalid.InvalidSearchQueryException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveAggregationDefinitions(java.util.Map parameters, java.lang.String authHandle,
                                                    java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.invalid.InvalidSearchQueryException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

}
