/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.oum.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for OrganizationalUnitHandler.
 */
public interface OrganizationalUnitHandlerRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/OrganizationalUnitHandler";
    public static final String JNDI_NAME = "ejb/OrganizationalUnitHandler";

    public OrganizationalUnitHandlerRemote create()
            throws CreateException, RemoteException;

}
