/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.oum.ejb.interfaces;

import de.escidoc.core.common.business.fedora.EscidocBinaryContent;
import de.escidoc.core.common.exceptions.EscidocException;
import de.escidoc.core.common.exceptions.application.invalid.InvalidSearchQueryException;
import de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException;
import de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException;
import de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException;
import de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException;
import de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException;
import de.escidoc.core.common.exceptions.application.missing.MissingElementValueException;
import de.escidoc.core.common.exceptions.application.missing.MissingMdRecordException;
import de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException;
import de.escidoc.core.common.exceptions.application.notfound.MdRecordNotFoundException;
import de.escidoc.core.common.exceptions.application.notfound.OperationNotFoundException;
import de.escidoc.core.common.exceptions.application.notfound.OrganizationalUnitNotFoundException;
import de.escidoc.core.common.exceptions.application.security.AuthenticationException;
import de.escidoc.core.common.exceptions.application.security.AuthorizationException;
import de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException;
import de.escidoc.core.common.exceptions.application.violated.OrganizationalUnitHasChildrenException;
import de.escidoc.core.common.exceptions.application.violated.OrganizationalUnitHierarchyViolationException;
import de.escidoc.core.common.exceptions.system.SystemException;
import org.springframework.security.context.SecurityContext;

import javax.ejb.EJBObject;
import java.rmi.RemoteException;
import java.util.Map;

/**
 * Remote interface for OrganizationalUnitHandler.
 */
public interface OrganizationalUnitHandlerRemote extends EJBObject {

    public String ingest(String xmlData,
                                   SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            SystemException,
            MissingAttributeValueException,
            MissingElementValueException,
            OrganizationalUnitNotFoundException,
            InvalidXmlException,
            InvalidStatusException,
            EscidocException, RemoteException;

    public String ingest(String xmlData, String authHandle, Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            SystemException,
            MissingAttributeValueException,
            MissingElementValueException,
            OrganizationalUnitNotFoundException,
            InvalidXmlException,
            InvalidStatusException,
            EscidocException, RemoteException;

    public String create(String xml,
                                   SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            SystemException,
            MissingAttributeValueException,
            MissingElementValueException,
            OrganizationalUnitNotFoundException,
            InvalidStatusException,
            XmlCorruptedException,
            XmlSchemaValidationException,
            MissingMdRecordException, RemoteException;

    public String create(String xml, String authHandle, Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            SystemException,
            MissingAttributeValueException,
            MissingElementValueException,
            OrganizationalUnitNotFoundException,
            InvalidStatusException,
            XmlCorruptedException,
            XmlSchemaValidationException,
            MissingMdRecordException, RemoteException;

    public void delete(String id, SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            InvalidStatusException,
            OrganizationalUnitHasChildrenException,
            SystemException, RemoteException;

    public void delete(String id, String authHandle, Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            InvalidStatusException,
            OrganizationalUnitHasChildrenException,
            SystemException, RemoteException;

    public String update(String id, String user,
                                   SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException,
            OptimisticLockingException,
            OrganizationalUnitHierarchyViolationException,
            InvalidXmlException,
            MissingElementValueException,
            InvalidStatusException, RemoteException;

    public String update(String id, String user, String authHandle,
                                   Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException,
            OptimisticLockingException,
            OrganizationalUnitHierarchyViolationException,
            InvalidXmlException,
            MissingElementValueException,
            InvalidStatusException, RemoteException;

    public String updateMdRecords(String id, String xml,
                                            SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            InvalidXmlException,
            InvalidStatusException,
            MissingMethodParameterException,
            OptimisticLockingException,
            OrganizationalUnitNotFoundException,
            MissingElementValueException,
            SystemException, RemoteException;

    public String updateMdRecords(String id, String xml, String authHandle,
                                            Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            InvalidXmlException,
            InvalidStatusException,
            MissingMethodParameterException,
            OptimisticLockingException,
            OrganizationalUnitNotFoundException,
            MissingElementValueException,
            SystemException, RemoteException;

    public String updateParents(String id, String xml,
                                          SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            InvalidXmlException,
            MissingMethodParameterException,
            OptimisticLockingException,
            OrganizationalUnitHierarchyViolationException,
            OrganizationalUnitNotFoundException,
            MissingElementValueException,
            SystemException,
            InvalidStatusException, RemoteException;

    public String updateParents(String id, String xml, String authHandle,
                                          Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            InvalidXmlException,
            MissingMethodParameterException,
            OptimisticLockingException,
            OrganizationalUnitHierarchyViolationException,
            OrganizationalUnitNotFoundException,
            MissingElementValueException,
            SystemException,
            InvalidStatusException, RemoteException;

    public String retrieve(String id,
                                     SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrieve(String id, String authHandle, Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrieveProperties(String id,
                                               SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrieveProperties(String id, String authHandle,
                                               Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public EscidocBinaryContent retrieveResource(String id,
                                                                                        String resourceName,
                                                                                        SecurityContext securityContext)
            throws OrganizationalUnitNotFoundException,
            AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OperationNotFoundException,
            SystemException, RemoteException;

    public EscidocBinaryContent retrieveResource(String id,
                                                                                        String resourceName,
                                                                                        String authHandle,
                                                                                        Boolean restAccess)
            throws OrganizationalUnitNotFoundException,
            AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OperationNotFoundException,
            SystemException, RemoteException;

    public String retrieveResources(String ouId,
                                              SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrieveResources(String ouId, String authHandle,
                                              Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrieveMdRecords(String id,
                                              SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrieveMdRecords(String id, String authHandle,
                                              Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrieveMdRecord(String id, String name,
                                             SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            MdRecordNotFoundException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrieveMdRecord(String id, String name, String authHandle,
                                             Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            MdRecordNotFoundException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrieveParents(String id,
                                            SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrieveParents(String id, String authHandle,
                                            Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrieveParentObjects(String ouId,
                                                  SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrieveParentObjects(String ouId, String authHandle,
                                                  Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrieveSuccessors(String id,
                                               SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrieveSuccessors(String id, String authHandle,
                                               Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrieveChildObjects(String ouId,
                                                 SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrieveChildObjects(String ouId, String authHandle,
                                                 Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            SystemException, RemoteException;

    public String retrievePathList(String ouId,
                                             SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            OrganizationalUnitNotFoundException,
            SystemException,
            MissingMethodParameterException,
            RemoteException;

    public String retrievePathList(String ouId, String authHandle,
                                             Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            OrganizationalUnitNotFoundException,
            SystemException,
            MissingMethodParameterException,
            RemoteException;

    public String retrieveOrganizationalUnits(Map filter,
                                                        SecurityContext securityContext)
            throws MissingMethodParameterException,
            SystemException,
            InvalidSearchQueryException,
            InvalidXmlException, RemoteException;

    public String retrieveOrganizationalUnits(Map filter, String authHandle,
                                                        Boolean restAccess)
            throws MissingMethodParameterException,
            SystemException,
            InvalidSearchQueryException,
            InvalidXmlException, RemoteException;

    public String close(String id, String taskParam,
                                  SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            InvalidStatusException,
            SystemException,
            OptimisticLockingException,
            InvalidXmlException, RemoteException;

    public String close(String id, String taskParam, String authHandle,
                                  Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            InvalidStatusException,
            SystemException,
            OptimisticLockingException,
            InvalidXmlException, RemoteException;

    public String open(String id, String taskParam,
                                 SecurityContext securityContext)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            InvalidStatusException,
            SystemException,
            OptimisticLockingException,
            InvalidXmlException, RemoteException;

    public String open(String id, String taskParam, String authHandle,
                                 Boolean restAccess)
            throws AuthenticationException,
            AuthorizationException,
            MissingMethodParameterException,
            OrganizationalUnitNotFoundException,
            InvalidStatusException,
            SystemException,
            OptimisticLockingException,
            InvalidXmlException, RemoteException;

}
