/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.oum.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * Local home interface for OrganizationalUnitHandler.
 */
public interface OrganizationalUnitHandlerLocalHome extends EJBLocalHome {

    public static final String COMP_NAME = "java:comp/env/ejb/OrganizationalUnitHandlerLocal";
    public static final String JNDI_NAME = "ejb/OrganizationalUnitHandlerLocal";

    public OrganizationalUnitHandlerLocal create() throws CreateException;

}
