/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.om.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * Local home interface for ContentRelationHandler.
 */
public interface ContentRelationHandlerLocalHome extends EJBLocalHome {

    public static final String COMP_NAME = "java:comp/env/ejb/ContentRelationHandlerLocal";
    public static final String JNDI_NAME = "ejb/ContentRelationHandlerLocal";

    public ContentRelationHandlerLocal create() throws CreateException;

}
