/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.om.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for ContainerHandler.
 */
public interface ContainerHandlerRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/ContainerHandler";
    public static final String JNDI_NAME = "ejb/ContainerHandler";

    public ContainerHandlerRemote create()
            throws CreateException, RemoteException;

}
