/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.om.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for ContextHandler.
 */
public interface ContextHandlerRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/ContextHandler";
    public static final String JNDI_NAME = "ejb/ContextHandler";

    public ContextHandlerRemote create()
            throws CreateException, RemoteException;

}
