/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.om.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for FedoraDescribeDeviationHandler.
 */
public interface FedoraDescribeDeviationHandlerRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/FedoraDescribeDeviationHandler";
    public static final String JNDI_NAME = "ejb/FedoraDescribeDeviationHandler";

    public FedoraDescribeDeviationHandlerRemote create()
            throws CreateException, RemoteException;

}
