/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.om.ejb.interfaces;

import de.escidoc.core.common.business.fedora.EscidocBinaryContent;
import org.springframework.security.context.SecurityContext;

import javax.ejb.EJBLocalObject;
import java.util.Map;

/**
 * Local interface for FedoraRestDeviationHandler.
 */
public interface FedoraRestDeviationHandlerLocal extends EJBLocalObject {

    public EscidocBinaryContent getDatastreamDissemination(String pid,
                                                                                                  String dsID,
                                                                                                  Map parameters,
                                                                                                  SecurityContext securityContext)
            throws Exception;

    public EscidocBinaryContent getDatastreamDissemination(String pid,
                                                                                                  String dsID,
                                                                                                  Map parameters,
                                                                                                  String authHandle,
                                                                                                  Boolean restAccess)
            throws Exception;

    public String export(String pid, Map parameters,
                                   SecurityContext securityContext)
            throws Exception;

    public String export(String pid, Map parameters, String authHandle,
                                   Boolean restAccess) throws Exception;

    public void cache(String pid, String xml,
                      SecurityContext securityContext) throws Exception;

    public void cache(String pid, String xml, String authHandle,
                      Boolean restAccess) throws Exception;

    public void removeFromCache(String pid,
                                SecurityContext securityContext)
            throws Exception;

    public void removeFromCache(String pid, String authHandle, Boolean restAccess)
            throws Exception;

    public void replaceInCache(String pid, String xml,
                               SecurityContext securityContext)
            throws Exception;

    public void replaceInCache(String pid, String xml, String authHandle,
                               Boolean restAccess) throws Exception;

}
