/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.om.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * Local home interface for IngestHandler.
 */
public interface IngestHandlerLocalHome extends EJBLocalHome {

    public static final String COMP_NAME = "java:comp/env/ejb/IngestHandlerLocal";
    public static final String JNDI_NAME = "ejb/IngestHandlerLocal";

    public IngestHandlerLocal create() throws CreateException;

}
