/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.om.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for IngestHandler.
 */
public interface IngestHandlerRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/IngestHandler";
    public static final String JNDI_NAME = "ejb/IngestHandler";

    public IngestHandlerRemote create()
            throws CreateException, RemoteException;

}
