/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.om.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * Local home interface for ItemHandler.
 */
public interface ItemHandlerLocalHome extends EJBLocalHome {

    public static final String COMP_NAME = "java:comp/env/ejb/ItemHandlerLocal";
    public static final String JNDI_NAME = "ejb/ItemHandlerLocal";

    public ItemHandlerLocal create() throws CreateException;

}
