/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.om.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for ItemHandler.
 */
public interface ItemHandlerRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/ItemHandler";
    public static final String JNDI_NAME = "ejb/ItemHandler";

    public ItemHandlerRemote create()
            throws CreateException, RemoteException;

}
