/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.om.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for SemanticStoreHandler.
 */
public interface SemanticStoreHandlerRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/SemanticStoreHandler";
    public static final String JNDI_NAME = "ejb/SemanticStoreHandler";

    public SemanticStoreHandlerRemote create()
            throws CreateException, RemoteException;

}
