/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.om.service;

/**
 * Service endpoint interface for ContainerHandler.
 */
public interface ContainerHandlerService extends java.rmi.Remote {

    java.lang.String create(java.lang.String xmlData,
                            org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContextNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ContentModelNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.ReferencedResourceNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.RelationPredicateNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMdRecordException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            java.rmi.RemoteException;

    java.lang.String create(java.lang.String xmlData, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContextNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ContentModelNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.ReferencedResourceNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.RelationPredicateNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMdRecordException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            java.rmi.RemoteException;

    void delete(java.lang.String id, org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException, java.rmi.RemoteException;

    void delete(java.lang.String id, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException, java.rmi.RemoteException;

    java.lang.String retrieve(java.lang.String id, org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieve(java.lang.String id, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String update(java.lang.String id, java.lang.String xmlData,
                            org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.ReferencedResourceNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.RelationPredicateNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.missing.MissingMdRecordException, java.rmi.RemoteException;

    java.lang.String update(java.lang.String id, java.lang.String xmlData, java.lang.String authHandle,
                            java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.ReferencedResourceNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.RelationPredicateNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.missing.MissingMdRecordException, java.rmi.RemoteException;

    java.lang.String retrieveMembers(java.lang.String id, java.util.Map filter,
                                     org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidSearchQueryException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveMembers(java.lang.String id, java.util.Map filter, java.lang.String authHandle,
                                     java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidSearchQueryException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveTocs(java.lang.String id, java.util.Map filter,
                                  org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidSearchQueryException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveTocs(java.lang.String id, java.util.Map filter, java.lang.String authHandle,
                                  java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidSearchQueryException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String addMembers(java.lang.String id, java.lang.String taskParam,
                                org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContextException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            java.rmi.RemoteException;

    java.lang.String addMembers(java.lang.String id, java.lang.String taskParam, java.lang.String authHandle,
                                java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContextException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            java.rmi.RemoteException;

    java.lang.String addTocs(java.lang.String id, java.lang.String taskParam,
                             org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContextException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            java.rmi.RemoteException;

    java.lang.String addTocs(java.lang.String id, java.lang.String taskParam, java.lang.String authHandle,
                             java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContextException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            java.rmi.RemoteException;

    java.lang.String removeMembers(java.lang.String id, java.lang.String taskParam,
                                   org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContextNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContextStatusException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidItemStatusException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException, java.rmi.RemoteException;

    java.lang.String removeMembers(java.lang.String id, java.lang.String taskParam, java.lang.String authHandle,
                                   java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContextNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContextStatusException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidItemStatusException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException, java.rmi.RemoteException;

    java.lang.String retrieveMdRecord(java.lang.String id, java.lang.String mdRecordId,
                                      org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.notfound.MdRecordNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveMdRecord(java.lang.String id, java.lang.String mdRecordId, java.lang.String authHandle,
                                      java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.notfound.MdRecordNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveMdRecords(java.lang.String id,
                                       org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveMdRecords(java.lang.String id, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveProperties(java.lang.String id,
                                        org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveProperties(java.lang.String id, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveStructMap(java.lang.String id,
                                       org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveStructMap(java.lang.String id, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveVersionHistory(java.lang.String id,
                                            org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveVersionHistory(java.lang.String id, java.lang.String authHandle,
                                            java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveParents(java.lang.String id,
                                     org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveParents(java.lang.String id, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveRelations(java.lang.String id,
                                       org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveRelations(java.lang.String id, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String release(java.lang.String id, java.lang.String lastModified,
                             org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    java.lang.String release(java.lang.String id, java.lang.String lastModified, java.lang.String authHandle,
                             java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    java.lang.String submit(java.lang.String id, java.lang.String lastModified,
                            org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    java.lang.String submit(java.lang.String id, java.lang.String lastModified, java.lang.String authHandle,
                            java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    java.lang.String withdraw(java.lang.String id, java.lang.String lastModified,
                              org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyWithdrawnException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    java.lang.String withdraw(java.lang.String id, java.lang.String lastModified, java.lang.String authHandle,
                              java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyWithdrawnException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    java.lang.String revise(java.lang.String id, java.lang.String lastModified,
                            org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException, java.rmi.RemoteException;

    java.lang.String revise(java.lang.String id, java.lang.String lastModified, java.lang.String authHandle,
                            java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException, java.rmi.RemoteException;

    java.lang.String lock(java.lang.String id, java.lang.String lastModified,
                          org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    java.lang.String lock(java.lang.String id, java.lang.String lastModified, java.lang.String authHandle,
                          java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    java.lang.String unlock(java.lang.String id, java.lang.String lastModified,
                            org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    java.lang.String unlock(java.lang.String id, java.lang.String lastModified, java.lang.String authHandle,
                            java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    java.lang.String moveToContext(java.lang.String containerId, java.lang.String taskParam,
                                   org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ContextNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String moveToContext(java.lang.String containerId, java.lang.String taskParam,
                                   java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ContextNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String createItem(java.lang.String containerId, java.lang.String xmlData,
                                org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingContentException,
            de.escidoc.core.common.exceptions.application.notfound.ContextNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ContentModelNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyElementViolationException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyAttributeViolationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.notfound.FileNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContextException,
            de.escidoc.core.common.exceptions.application.notfound.RelationPredicateNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ReferencedResourceNotFoundException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMdRecordException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException, java.rmi.RemoteException;

    java.lang.String createItem(java.lang.String containerId, java.lang.String xmlData, java.lang.String authHandle,
                                java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingContentException,
            de.escidoc.core.common.exceptions.application.notfound.ContextNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ContentModelNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyElementViolationException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyAttributeViolationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.notfound.FileNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContextException,
            de.escidoc.core.common.exceptions.application.notfound.RelationPredicateNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ReferencedResourceNotFoundException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMdRecordException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException, java.rmi.RemoteException;

    java.lang.String createContainer(java.lang.String containerId, java.lang.String xmlData,
                                     org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.notfound.ContextNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ContentModelNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContextException,
            de.escidoc.core.common.exceptions.application.notfound.RelationPredicateNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.notfound.ReferencedResourceNotFoundException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.missing.MissingMdRecordException, java.rmi.RemoteException;

    java.lang.String createContainer(java.lang.String containerId, java.lang.String xmlData,
                                     java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.notfound.ContextNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ContentModelNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContextException,
            de.escidoc.core.common.exceptions.application.notfound.RelationPredicateNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.notfound.ReferencedResourceNotFoundException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.missing.MissingMdRecordException, java.rmi.RemoteException;

    java.lang.String retrieveContainers(java.util.Map filter,
                                        org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidSearchQueryException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveContainers(java.util.Map filter, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidSearchQueryException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String addContentRelations(java.lang.String id, java.lang.String param,
                                         org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.notfound.ReferencedResourceNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.RelationPredicateNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyExistsException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            java.rmi.RemoteException;

    java.lang.String addContentRelations(java.lang.String id, java.lang.String param, java.lang.String authHandle,
                                         java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.notfound.ReferencedResourceNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.RelationPredicateNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyExistsException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            java.rmi.RemoteException;

    java.lang.String removeContentRelations(java.lang.String id, java.lang.String param,
                                            org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.notfound.ContentRelationNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException, java.rmi.RemoteException;

    java.lang.String removeContentRelations(java.lang.String id, java.lang.String param, java.lang.String authHandle,
                                            java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.notfound.ContentRelationNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException, java.rmi.RemoteException;

    java.lang.String assignObjectPid(java.lang.String id, java.lang.String param,
                                     org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    java.lang.String assignObjectPid(java.lang.String id, java.lang.String param, java.lang.String authHandle,
                                     java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    java.lang.String assignVersionPid(java.lang.String id, java.lang.String param,
                                      org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException, java.rmi.RemoteException;

    java.lang.String assignVersionPid(java.lang.String id, java.lang.String param, java.lang.String authHandle,
                                      java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContainerNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException, java.rmi.RemoteException;

}
