/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.om.service;

/**
 * Service endpoint interface for ItemHandler.
 */
public interface ItemHandlerService extends java.rmi.Remote {

    public java.lang.String create(java.lang.String xmlData,
                                   org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.missing.MissingContentException,
            de.escidoc.core.common.exceptions.application.notfound.ContextNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ContentModelNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyElementViolationException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyAttributeViolationException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.notfound.FileNotFoundException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.notfound.ReferencedResourceNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.RelationPredicateNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMdRecordException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException, java.rmi.RemoteException;

    public java.lang.String create(java.lang.String xmlData, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.missing.MissingContentException,
            de.escidoc.core.common.exceptions.application.notfound.ContextNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ContentModelNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyElementViolationException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyAttributeViolationException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.notfound.FileNotFoundException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.notfound.ReferencedResourceNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.RelationPredicateNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMdRecordException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException, java.rmi.RemoteException;

    public void delete(java.lang.String id, org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyPublishedException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public void delete(java.lang.String id, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyPublishedException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieve(java.lang.String id,
                                     org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieve(java.lang.String id, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String update(java.lang.String id, java.lang.String xmlData,
                                   org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.FileNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContextException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.violated.NotPublishedException,
            de.escidoc.core.common.exceptions.application.missing.MissingLicenceException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingContentException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyExistsException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.notfound.ReferencedResourceNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.RelationPredicateNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.missing.MissingMdRecordException, java.rmi.RemoteException;

    public java.lang.String update(java.lang.String id, java.lang.String xmlData, java.lang.String authHandle,
                                   java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.FileNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContextException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.violated.NotPublishedException,
            de.escidoc.core.common.exceptions.application.missing.MissingLicenceException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingContentException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyExistsException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.notfound.ReferencedResourceNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.RelationPredicateNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.missing.MissingMdRecordException, java.rmi.RemoteException;

    public java.lang.String createComponent(java.lang.String id, java.lang.String xmlData,
                                            org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.missing.MissingContentException,
            de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.notfound.FileNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            java.rmi.RemoteException;

    public java.lang.String createComponent(java.lang.String id, java.lang.String xmlData, java.lang.String authHandle,
                                            java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.missing.MissingContentException,
            de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.notfound.FileNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            java.rmi.RemoteException;

    public java.lang.String retrieveComponent(java.lang.String id, java.lang.String componentId,
                                              org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveComponent(java.lang.String id, java.lang.String componentId,
                                              java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveComponentMdRecords(java.lang.String id, java.lang.String componentId,
                                                       org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveComponentMdRecords(java.lang.String id, java.lang.String componentId,
                                                       java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveComponentMdRecord(java.lang.String id, java.lang.String componentId,
                                                      java.lang.String mdRecordId,
                                                      org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.MdRecordNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveComponentMdRecord(java.lang.String id, java.lang.String componentId,
                                                      java.lang.String mdRecordId, java.lang.String authHandle,
                                                      java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.MdRecordNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String updateComponent(java.lang.String id, java.lang.String componentId, java.lang.String xmlData,
                                            org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.notfound.FileNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.missing.MissingContentException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException, java.rmi.RemoteException;

    public java.lang.String updateComponent(java.lang.String id, java.lang.String componentId, java.lang.String xmlData,
                                            java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.notfound.FileNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.missing.MissingContentException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException, java.rmi.RemoteException;

    public java.lang.String retrieveComponents(java.lang.String id,
                                               org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveComponents(java.lang.String id, java.lang.String authHandle,
                                               java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveComponentProperties(java.lang.String id, java.lang.String componentId,
                                                        org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveComponentProperties(java.lang.String id, java.lang.String componentId,
                                                        java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String createMetadataRecord(java.lang.String id, java.lang.String xmlData,
                                                 org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.XmlSchemaNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    public java.lang.String createMetadataRecord(java.lang.String id, java.lang.String xmlData,
                                                 java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.XmlSchemaNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    public java.lang.String createMdRecord(java.lang.String id, java.lang.String xmlData,
                                           org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException, java.rmi.RemoteException;

    public java.lang.String createMdRecord(java.lang.String id, java.lang.String xmlData, java.lang.String authHandle,
                                           java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException, java.rmi.RemoteException;

    public java.lang.String retrieveMdRecord(java.lang.String id, java.lang.String mdRecordId,
                                             org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.MdRecordNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveMdRecord(java.lang.String id, java.lang.String mdRecordId,
                                             java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.MdRecordNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String updateMdRecord(java.lang.String id, java.lang.String mdRecordId, java.lang.String xmlData,
                                           org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.XmlSchemaNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.notfound.MdRecordNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException, java.rmi.RemoteException;

    public java.lang.String updateMdRecord(java.lang.String id, java.lang.String mdRecordId, java.lang.String xmlData,
                                           java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.XmlSchemaNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.notfound.MdRecordNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException, java.rmi.RemoteException;

    public java.lang.String retrieveMdRecords(java.lang.String id,
                                              org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveMdRecords(java.lang.String id, java.lang.String authHandle,
                                              java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveContentStreams(java.lang.String id,
                                                   org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveContentStreams(java.lang.String id, java.lang.String authHandle,
                                                   java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveContentStream(java.lang.String id, java.lang.String name,
                                                  org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.ContentStreamNotFoundException,
            java.rmi.RemoteException;

    public java.lang.String retrieveContentStream(java.lang.String id, java.lang.String name,
                                                  java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.ContentStreamNotFoundException,
            java.rmi.RemoteException;

    public java.lang.String retrieveProperties(java.lang.String id,
                                               org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveProperties(java.lang.String id, java.lang.String authHandle,
                                               java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveVersionHistory(java.lang.String id,
                                                   org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveVersionHistory(java.lang.String id, java.lang.String authHandle,
                                                   java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveParents(java.lang.String id,
                                            org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveParents(java.lang.String id, java.lang.String authHandle,
                                            java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveRelations(java.lang.String id,
                                              org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveRelations(java.lang.String id, java.lang.String authHandle,
                                              java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String release(java.lang.String id, java.lang.String lastModified,
                                    org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    public java.lang.String release(java.lang.String id, java.lang.String lastModified, java.lang.String authHandle,
                                    java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    public java.lang.String submit(java.lang.String id, java.lang.String lastModified,
                                   org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    public java.lang.String submit(java.lang.String id, java.lang.String lastModified, java.lang.String authHandle,
                                   java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    public java.lang.String revise(java.lang.String id, java.lang.String lastModified,
                                   org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException, java.rmi.RemoteException;

    public java.lang.String revise(java.lang.String id, java.lang.String lastModified, java.lang.String authHandle,
                                   java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException, java.rmi.RemoteException;

    public java.lang.String withdraw(java.lang.String id, java.lang.String lastModified,
                                     org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.NotPublishedException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyWithdrawnException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    public java.lang.String withdraw(java.lang.String id, java.lang.String lastModified, java.lang.String authHandle,
                                     java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.NotPublishedException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyWithdrawnException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    public java.lang.String lock(java.lang.String id, java.lang.String lastModified,
                                 org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException, java.rmi.RemoteException;

    public java.lang.String lock(java.lang.String id, java.lang.String lastModified, java.lang.String authHandle,
                                 java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException, java.rmi.RemoteException;

    public java.lang.String unlock(java.lang.String id, java.lang.String lastModified,
                                   org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    public java.lang.String unlock(java.lang.String id, java.lang.String lastModified, java.lang.String authHandle,
                                   java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException, java.rmi.RemoteException;

    public void deleteComponent(java.lang.String itemId, java.lang.String componentId,
                                org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException, java.rmi.RemoteException;

    public void deleteComponent(java.lang.String itemId, java.lang.String componentId, java.lang.String authHandle,
                                java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException, java.rmi.RemoteException;

    public java.lang.String moveToContext(java.lang.String id, java.lang.String taskParam,
                                          org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ContextNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String moveToContext(java.lang.String id, java.lang.String taskParam, java.lang.String authHandle,
                                          java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ContextNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveItems(java.util.Map filter,
                                          org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveItems(java.util.Map filter, java.lang.String authHandle,
                                          java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String assignVersionPid(java.lang.String id, java.lang.String taskParam,
                                             org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException, java.rmi.RemoteException;

    public java.lang.String assignVersionPid(java.lang.String id, java.lang.String taskParam,
                                             java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException, java.rmi.RemoteException;

    public java.lang.String assignObjectPid(java.lang.String id, java.lang.String taskParam,
                                            org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException, java.rmi.RemoteException;

    public java.lang.String assignObjectPid(java.lang.String id, java.lang.String taskParam,
                                            java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException, java.rmi.RemoteException;

    public java.lang.String assignContentPid(java.lang.String id, java.lang.String componentId,
                                             java.lang.String taskParam,
                                             org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException, java.rmi.RemoteException;

    public java.lang.String assignContentPid(java.lang.String id, java.lang.String componentId,
                                             java.lang.String taskParam, java.lang.String authHandle,
                                             java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException, java.rmi.RemoteException;

    public java.lang.String addContentRelations(java.lang.String id, java.lang.String param,
                                                org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.notfound.ReferencedResourceNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.RelationPredicateNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyExistsException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException, java.rmi.RemoteException;

    public java.lang.String addContentRelations(java.lang.String id, java.lang.String param,
                                                java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.notfound.ReferencedResourceNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.RelationPredicateNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyExistsException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException, java.rmi.RemoteException;

    public java.lang.String removeContentRelations(java.lang.String id, java.lang.String param,
                                                   org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.notfound.ContentRelationNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyDeletedException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException, java.rmi.RemoteException;

    public java.lang.String removeContentRelations(java.lang.String id, java.lang.String param,
                                                   java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.ItemNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.ComponentNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidStatusException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.notfound.ContentRelationNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyDeletedException,
            de.escidoc.core.common.exceptions.application.violated.LockingException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyViolationException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.violated.ReadonlyVersionException, java.rmi.RemoteException;

}
