/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.om.service;

/**
 * Service endpoint interface for SemanticStoreHandler.
 */
public interface SemanticStoreHandlerService extends java.rmi.Remote {

    java.lang.String spo(java.lang.String taskParam,
                         org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidTripleStoreQueryException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidTripleStoreOutputFormatException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException, java.rmi.RemoteException;

    java.lang.String spo(java.lang.String taskParam, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidTripleStoreQueryException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidTripleStoreOutputFormatException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidXmlException,
            de.escidoc.core.common.exceptions.application.missing.MissingElementValueException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException, java.rmi.RemoteException;

}
