/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.oai.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

/**
 * Local home interface for SetDefinitionHandler.
 */
public interface SetDefinitionHandlerLocalHome extends EJBLocalHome {

    public static final String COMP_NAME = "java:comp/env/ejb/SetDefinitionHandlerLocal";
    public static final String JNDI_NAME = "ejb/SetDefinitionHandlerLocal";

    public SetDefinitionHandlerLocal create() throws CreateException;

}
