/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.oai.ejb.interfaces;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import java.rmi.RemoteException;

/**
 * Home interface for SetDefinitionHandler.
 */
public interface SetDefinitionHandlerRemoteHome extends EJBHome {

    public static final String COMP_NAME = "java:comp/env/ejb/SetDefinitionHandler";
    public static final String JNDI_NAME = "ejb/SetDefinitionHandler";

    public SetDefinitionHandlerRemote create()
            throws CreateException, RemoteException;

}
