/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.aa.service;

/**
 * Service endpoint interface for PolicyDecisionPoint.
 */
public interface PolicyDecisionPointService extends java.rmi.Remote {

    public java.lang.String evaluate(java.lang.String requestsXml,
                                     org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.ResourceNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String evaluate(java.lang.String requestsXml, java.lang.String authHandle,
                                     java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.ResourceNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public void touch(org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public void touch(java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

}
