/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.aa.service;

/**
 * Service endpoint interface for RoleHandler.
 */
public interface RoleHandlerService extends java.rmi.Remote {

    public java.lang.String create(java.lang.String xmlData,
                                   org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.violated.UniqueConstraintViolationException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String create(java.lang.String xmlData, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.violated.UniqueConstraintViolationException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public void delete(java.lang.String id, org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.notfound.RoleNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.RoleInUseViolationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public void delete(java.lang.String id, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.notfound.RoleNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.RoleInUseViolationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieve(java.lang.String id,
                                     org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.RoleNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieve(java.lang.String id, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.RoleNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String update(java.lang.String id, java.lang.String xmlData,
                                   org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.RoleNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.violated.UniqueConstraintViolationException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String update(java.lang.String id, java.lang.String xmlData, java.lang.String authHandle,
                                   java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.RoleNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.violated.UniqueConstraintViolationException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    public java.lang.String retrieveRoles(java.util.Map filter,
                                          org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidSearchQueryException, java.rmi.RemoteException;

    public java.lang.String retrieveRoles(java.util.Map filter, java.lang.String authHandle,
                                          java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidSearchQueryException, java.rmi.RemoteException;

}
