/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.aa.service;

/**
 * Service endpoint interface for UserGroupHandler.
 */
public interface UserGroupHandlerService extends java.rmi.Remote {

    java.lang.String create(java.lang.String xmlData,
                            org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.violated.UniqueConstraintViolationException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String create(java.lang.String xmlData, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.violated.UniqueConstraintViolationException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    void delete(java.lang.String groupId, org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    void delete(java.lang.String groupId, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieve(java.lang.String groupId,
                              org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieve(java.lang.String groupId, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String update(java.lang.String groupId, java.lang.String xmlData,
                            org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.UniqueConstraintViolationException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String update(java.lang.String groupId, java.lang.String xmlData, java.lang.String authHandle,
                            java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.UniqueConstraintViolationException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    void activate(java.lang.String groupId, java.lang.String taskParam,
                  org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.violated.AlreadyActiveException,
            de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    void activate(java.lang.String groupId, java.lang.String taskParam, java.lang.String authHandle,
                  java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.violated.AlreadyActiveException,
            de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    void deactivate(java.lang.String groupId, java.lang.String taskParam,
                    org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.violated.AlreadyDeactiveException,
            de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    void deactivate(java.lang.String groupId, java.lang.String taskParam, java.lang.String authHandle,
                    java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.violated.AlreadyDeactiveException,
            de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveCurrentGrants(java.lang.String userGroupId,
                                           org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveCurrentGrants(java.lang.String userGroupId, java.lang.String authHandle,
                                           java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String createGrant(java.lang.String groupId, java.lang.String grantXML,
                                 org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.violated.AlreadyExistsException,
            de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidScopeException,
            de.escidoc.core.common.exceptions.application.notfound.RoleNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String createGrant(java.lang.String groupId, java.lang.String grantXML, java.lang.String authHandle,
                                 java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.violated.AlreadyExistsException,
            de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidScopeException,
            de.escidoc.core.common.exceptions.application.notfound.RoleNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    void revokeGrant(java.lang.String groupId, java.lang.String grantId, java.lang.String taskParam,
                     org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.GrantNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyRevokedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    void revokeGrant(java.lang.String groupId, java.lang.String grantId, java.lang.String taskParam,
                     java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.GrantNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyRevokedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveGrant(java.lang.String groupId, java.lang.String grantId,
                                   org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.GrantNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveGrant(java.lang.String groupId, java.lang.String grantId, java.lang.String authHandle,
                                   java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.GrantNotFoundException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    void revokeGrants(java.lang.String groupId, java.lang.String taskParam,
                      org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.GrantNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyRevokedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    void revokeGrants(java.lang.String groupId, java.lang.String taskParam, java.lang.String authHandle,
                      java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.GrantNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.AlreadyRevokedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.missing.MissingAttributeValueException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveResources(java.lang.String groupId,
                                       org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveResources(java.lang.String groupId, java.lang.String authHandle,
                                       java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveUserGroups(java.util.Map filter,
                                        org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidSearchQueryException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String retrieveUserGroups(java.util.Map filter, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidSearchQueryException,
            de.escidoc.core.common.exceptions.system.SystemException, java.rmi.RemoteException;

    java.lang.String addSelectors(java.lang.String groupId, java.lang.String taskParam,
                                  org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.notfound.OrganizationalUnitNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.UserAccountNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.violated.UserGroupHierarchyViolationException,
            java.rmi.RemoteException;

    java.lang.String addSelectors(java.lang.String groupId, java.lang.String taskParam, java.lang.String authHandle,
                                  java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.notfound.OrganizationalUnitNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.UserAccountNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.invalid.InvalidContentException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.violated.UserGroupHierarchyViolationException,
            java.rmi.RemoteException;

    java.lang.String removeSelectors(java.lang.String groupId, java.lang.String taskParam,
                                     org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.notfound.UserAccountNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.OrganizationalUnitNotFoundException,
            java.rmi.RemoteException;

    java.lang.String removeSelectors(java.lang.String groupId, java.lang.String taskParam, java.lang.String authHandle,
                                     java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.invalid.XmlCorruptedException,
            de.escidoc.core.common.exceptions.application.invalid.XmlSchemaValidationException,
            de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            de.escidoc.core.common.exceptions.application.security.AuthorizationException,
            de.escidoc.core.common.exceptions.system.SystemException,
            de.escidoc.core.common.exceptions.application.notfound.UserGroupNotFoundException,
            de.escidoc.core.common.exceptions.application.violated.OptimisticLockingException,
            de.escidoc.core.common.exceptions.application.missing.MissingMethodParameterException,
            de.escidoc.core.common.exceptions.application.notfound.UserAccountNotFoundException,
            de.escidoc.core.common.exceptions.application.notfound.OrganizationalUnitNotFoundException,
            java.rmi.RemoteException;

}
