/*
 * Generated by XDoclet - Do not edit!
 */
package de.escidoc.core.aa.service;

import de.escidoc.core.common.exceptions.system.SystemException;

/**
 * Service endpoint interface for UserManagementWrapper.
 */
public interface UserManagementWrapperService extends java.rmi.Remote {

    void logout(org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            SystemException, java.rmi.RemoteException;

    void logout(java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            SystemException, java.rmi.RemoteException;

    void initHandleExpiryTimestamp(java.lang.String handle,
                                   org.springframework.security.context.SecurityContext securityContext)
            throws de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            SystemException, java.rmi.RemoteException;

    void initHandleExpiryTimestamp(java.lang.String handle, java.lang.String authHandle, java.lang.Boolean restAccess)
            throws de.escidoc.core.common.exceptions.application.security.AuthenticationException,
            SystemException, java.rmi.RemoteException;

}
